paths:
  uploads: uploads
  uploads_use_relative_path: false
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    description: ''
    icon: notes
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  archives:
    path: _archives
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  content:
    type: text
    options:
      styles: /editor.css
      blockquote: true
      horizontalrule: true
      format: p h1 h2 h3 h4 h5 h6
      bold: true
      italic: true
      numberedlist: true
      bulletedlist: true
      code: true
      table: true
      right: right
      center: center
      left: left
      embed: true
      link: true
      undo: true
      redo: true
      underline: true
      strike: true
      image: true
    cascade: true
_editables:
  text:
    allow_custom_markup: false
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
      uploads:
      uploads_filename:
      uploads_use_relative_path:
      static:
      dam_uploads:
      dam_uploads_filename:
      dam_static:
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    undo: true
  image:
    expandable: true
    height: 0
    image_size_attributes: true
    mime_type:
    paths:
      uploads:
      uploads_filename:
      uploads_use_relative_path:
      static:
      dam_uploads:
      dam_uploads_filename:
      dam_static:
    resize_style: contain
    width:
  link:
    paths:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center:
    code:
    copyformatting:
    embed:
    expandable: true
    format:
    height:
    horizontalrule:
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify:
    left:
    link: true
    mime_type:
    numberedlist: true
    outdent: true
    paths:
    redo: true
    removeformat: true
    resize_style: contain
    right:
    snippet: true
    strike: true
    styles:
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
    width:
data_config: {}
timezone: Africa/Cairo
